### ISSUE TITLE
Failed types dependencies reconstructions

### ISSUE THREAD

**Issue by dvarrazzo** [perseas/Pyrseas#100]
Steps to reproduce, attempt 1: then I'll see if I can reproduce it without the ltree library installed, for test suite sake.

```
-- inside an empty database called 'pyrseas':
create schema xact;
create type ltree;
CREATE FUNCTION ltree_in(cstring) RETURNS ltree
    LANGUAGE c STRICT
    AS '$libdir/ltree', 'ltree_in';
ALTER FUNCTION ltree_in(cstring) OWNER TO postgres;
CREATE FUNCTION ltree_out(ltree) RETURNS cstring
    LANGUAGE c STRICT
    AS '$libdir/ltree', 'ltree_out';
ALTER FUNCTION ltree_out(ltree) OWNER TO postgres;
CREATE TYPE ltree (
    INPUT = ltree_in,
    OUTPUT = ltree_out,
    INTERNALLENGTH = variable,
    ALIGNMENT = int4,
    STORAGE = extended,
    CATEGORY = 'U');
CREATE TYPE xact.split_edit AS (    id integer,
    account_code ltree,
    amount numeric,
    amount_xn numeric,
    description text);
```

Try to dump it and recreate in an empty database:

```
dbtoyaml -U postgres pyrseas | yamltodb -U postgres postgres
```

This result in the generation of:

```
ALTER SCHEMA xact OWNER TO postgres;

CREATE TYPE xact.split_edit AS (    id integer,
    account_code ltree,
    amount numeric,
    amount_xn numeric,
    description text);

ALTER TYPE xact.split_edit OWNER TO postgres;

CREATE TYPE ltree;
... 
```

that will fail to restore xact.split_edit as the type ltree has not been created yet.

**Comment by jmafc** [comment]
@dvarrazzo Since this issue is what led to your creating the `deptrack` branch, and that has been essentially completed and merged into `master` I think we can safely close it.  Otherwise, the most we could do is verify that the initially reported test case has been corrected. I'll wait a couple days before closing it. In any case, if there are still unresolved dependency problems, it would be more appropriate to open new specific issues.

**Comment by jmafc** [comment]
@dvarrazzo Closing this issue now.  I have tested the synthetic test case that you provided in the second comment and, against current master, the `ltree` type gets created before `xact.split_edit`.
