### ISSUE TITLE
Can Pyrseas porting to other DB ?

### ISSUE THREAD

**Issue by yikaus** [perseas/Pyrseas#137]
Really like the feature of dbtoyaml and yamltodb , is it possible for Pyrseas  to porting to other DB like Oracle ? by refactoring the db connection ? 

Thanks

**Comment by jmafc** [comment]
Four years ago, in the post [More Database Tools?](https://pyrseas.wordpress.com/2012/03/05/more-database-tools/) I toyed with the idea of creating an `oratoyaml` tool, albeit the intent was to use it more to convert Oracle (or other databases) to Postgres (and thus there would not be a `yamltoora`). Also, one of our users in Spain did discuss the possibility of porting Pyrseas to work on SQL Server and I did give him some hints, but I never followed up on what happened.

Unfortunately, porting the db connection to talk to Oracle would not be sufficient. Pyrseas queries the internal Postgres system catalogs (rather than the `information_schema` catalogs). So you would have to replace those queries at the very least. So you'd have to rewrite the query starting at https://github.com/perseas/Pyrseas/blob/master/pyrseas/dbobject/table.py#L662 by referring to Oracle's `ALL_TABLES` and so forth.  Then you'd also have to take care of differences between Oracle and Postgres. For example, Postgres allows tables to inherit from other tables, Oracle has partitions, Postgres has a multitude of object types (e..g., FDW, textsearch, domains/enum types/composites, etc.), Oracle has synonyms.

**Comment by jmafc** [comment]
I forgot another porting step: if you want a `yamltodb` (or `yamltoora`) that talks to Oracle, it will also be necessary to adjust the SQL syntax generated by `yamltodb` to make it Oracle-compatible.

**Comment by yikaus** [comment]
Thanks Joe , It seems very costly work around sql refactor . :-) 

Anyway , it was a great work for doing a SQL diff style DB migration tool , really like it.

Cheers

**Comment by jmafc** [comment]
You're welcome.
