### ISSUE TITLE
dbtoyaml create index concurrently

### ISSUE THREAD

**Issue by fishpen0** [perseas/Pyrseas#193]
How should I modify the `indexes` section of a database.yaml file to ensure when I run dbtoyaml, that pyrseas runs `CREATE INDEX CONCURRENTLY` instead of just `CREATE INDEX`

**Comment by jmafc** [comment]
@fishpen0 The YAML file is (more or less) a reflection of the PG catalogs, i.e., [pg_index](https://www.postgresql.org/docs/current/static/catalog-pg-index.html) in this case. There is no indication in the catalogs whether an index can or should be created concurrently.
The easiest way to get concurrent index creation may be to use a `sed` script, e.g., `sed 's/CREATE INDEX /CREATE INDEX CONCURRENTLY /g'` applied to the `yamltodb` SQL output before handing it over to `psql`.
Otherwise, we would have to add a command line option or a configuration option so that `yamltodb` would emit CONCURRENTLY for all (or if desired, a subset of the) indexes.

**Comment by jmafc** [comment]
@fishpen0 Unless you want Pyrseas to add command line option as mentioned above, we will be closing this issue. Please see https://pyrseas.wordpress.com/2018/09/12/the-future-of-pyrseas-revisited/
