### ISSUE TITLE
dbtoyaml fails with psycopg2.ProgrammingError

### ISSUE THREAD

**Issue by andreypopp** [perseas/Pyrseas#28]
The following query doesn't work with my PostgreSQL 9.0.4 setup:

```
psycopg2.ProgrammingError: ('cannot cast type regclass to name
LINE 2: ...        CASE WHEN contypid = 0 THEN conrelid::regclass::name
                                                                 ^
', "SELECT nspname AS schema,
                  CASE WHEN contypid = 0 THEN conrelid::regclass::name
                       ELSE contypid::regtype::name END AS table,
                  conname AS name,
                  CASE WHEN contypid != 0 THEN 'd' ELSE '' END AS target,
                  contype AS type, conkey AS keycols,
                  condeferrable AS deferrable,
                  condeferred AS deferred,
                  confrelid::regclass AS ref_table, confkey AS ref_cols,
                  consrc AS expression, confupdtype AS on_update,
                  confdeltype AS on_delete, amname AS access_method,
                  obj_description(c.oid, 'pg_constraint') AS description
           FROM pg_constraint c
                JOIN pg_namespace ON (connamespace = pg_namespace.oid)
                LEFT JOIN pg_class on (conname = relname)
                LEFT JOIN pg_am on (relam = pg_am.oid)
           WHERE (nspname != 'pg_catalog' AND nspname != 'information_schema')
                 AND conislocal
           ORDER BY schema, 2, name")
```

**Comment by feikesteenbergen** [comment]
I'm unsure this issue needs to be reopened, but for anyone having this issue in the future, the following might be useful.

We ran into this issue recently. Some debugging showed us that the cause is that we have a table in the public schema called name. The solution for this query would be to fully qualify the cast to name, so.

```
feike=# CREATE TABLE public.name(i int);
CREATE TABLE
feike=# SELECT 0::regclass::name;
 name
------
 -
(1 row)

feike=# SET search_path TO public, pg_catalog;
SET
feike=# SELECT 0::regclass::name;
ERROR:  cannot cast type regclass to name
LINE 1: SELECT 0::regclass::name;
                          ^
feike=# SELECT 0::regclass::pg_catalog.name;
 name
------
 -
(1 row)
```

**Comment by feikesteenbergen** [comment]
@jmafc Could you create a new release containing this (and other) bugfixes? We're currently running the latest release https://github.com/perseas/Pyrseas/releases/tag/v0.7.3, but this fix is not part of that release.

**Comment by jmafc** [comment]
@feikesteenbergen I'm a bit reluctant to creating a new 0.7 maintenance release because (a) we're in the home stretch of work for release 0.8 (I estimate that in about one month we'll be done with dependency tracking and in another month we'll be able to add PG 10 support) and (b) there are only two other bugfixes in the r0.7 branch (three commits, for issues #155 and #157). However, I do seem to recall that there was some other (probably closed) issue for which somebody had asked another 0.7 release, so I'll try to track that down.

**Comment by jmafc** [comment]
The issue that someone had also asked for a 0.7 maintenance release was #160. One of the persons who asked apparently decided to use the master branch for the time being.
