### ISSUE TITLE
SERIAL columns

### ISSUE THREAD

**Issue by waldiTM** [perseas/Pyrseas#7]
Please support converting sequences created as SERIAL columns back.

**Comment by pyoner** [comment]
I have yaml spec:
schema fhub:
  table market:
    columns:
      - id:
          type: serial
      - name:
          type: text
          not_null: true
      - link:
          type: text
          not_null: true
      - feed_link:
          type: text
          not_null: true
    primary_key:
      market_pkey:
        columns:
          - id
    unique_constraints:
      market_name_key:
        columns:
          - name
      market_link_key:
        columns:
          - link
      market_feed_link_key:
        columns:
          - feed_link

When I run first time `yamltodb` it create table successfull, psql output:
\dS+ fhub.market
                                                  Table "fhub.market"
  Column   |  Type   |                        Modifiers                         | Storage  | Stats target | Description 
-----------+---------+----------------------------------------------------------+----------+--------------+-------------
 id        | integer | not null default nextval('fhub.market_id_seq'::regclass) | plain    |              | 
 name      | text    | not null                                                 | extended |              | 
 link      | text    | not null                                                 | extended |              | 
 feed_link | text    | not null                                                 | extended |              | 
Indexes:
    "market_pkey" PRIMARY KEY, btree (id)
    "market_feed_link_key" UNIQUE CONSTRAINT, btree (feed_link)
    "market_link_key" UNIQUE CONSTRAINT, btree (link)
    "market_name_key" UNIQUE CONSTRAINT, btree (name)
Has OIDs: no

But if run second time `yamltodb` without applying changes to db it output:
BEGIN;
ALTER TABLE fhub.market
    ALTER COLUMN id DROP NOT NULL, ALTER COLUMN id TYPE serial, ALTER COLUMN id DROP DEFAULT;

COMMIT;

it drop not null and change column type to **serial**!

**Comment by jmafc** [comment]
I'm afraid that this is a side effect of using a manually created YAML input file. I'm assuming this because I believe the spec:

```yaml
    columns:
      - id:
          type: serial
```
was *not* generated by `dbtoyaml`. If you run `dbtoyaml`, I would expect the following instead:

```yaml
    columns:
    - id:
        default: nextval('market_id_seq'::regclass)
        not_null: true
        type: integer
```
Then if you run `yamltodb` with this input, no `ALTER TABLE` would be generated.

The first time you ran `yamltodb` with the input `type: serial', you should have seen SQL such as:

```sql
CREATE TABLE market (
    id serial, ...);
```
However, although PG accepts this, it instead creates the `id` column as `INTEGER NOT NULL`, creates a sequence `market_id_seq` and alters the column to default to the nextval of that sequence (it also alters the sequence to be owned by `market.id`).

If you run `yamltodb` with the input `type: serial`, `yamltodb` compares that to what is actually in the catalogs and (not knowing any better) attempts to issue statements to match the input spec as you reported.

I think that perhaps we could special-case `type: serial` (and SERIAL8) and report that it is a pseudo-datatype that shouldn't be used in the input YAML (the concern is that someone could actually define a serial datatype of their own).

**Comment by pyoner** [comment]
Yes, I manually create an yaml file.
Thank you for the answer!
